### ISSUE TITLE
[问题与 BUG 反馈] Android 11 版本的 ColorOS 适配

### ISSUE THREAD

**Issue by luckyzyx** [fankes/ColorOSNotifyIcon#15]
**系统版本(必填)**

Oneplus 9rt A12

**系统类型(请保留一个)**

* ColorOS12

**Android 版本(必填)**

Android 11
**模块版本(必填)**

1.52

**使用的 Xposed 框架名称与框架版本(必填)**

Lsp 1.8.0  6482  zygisk

**问题的具体描述**

前两天系统更新了，现在才发现lsp log，系统界面com.oplusos.systemui.statusbar.phone.OplusNotificationIconAreaController应该换成了com.android.systemui.statusbar.phone.NotificationIconAreaController，我找到了updateIconsForLayout方法

**提供模块问题 Log 或必要 Log**

<details><summary>展开查看</summary><pre><code>

java.lang.IllegalStateException: VariousClass match failed of those ["com.oplusos.systemui.statusbar.phone.OplusNotificationIconAreaController","com.coloros.systemui.statusbar.phone.ColorosNotificationIconAreaController"]
	at a3.b.a(P:7)
	at i3.b.k(P:1)
	at i3.b.m(P:1)
	at p1.d.r(P:8)
	at f3.a.q(P:2)
	at i3.b.p(P:1)
	at i3.b.o(P:1)
	at o1.a$a.c(P:11)
	at o1.a$a.b(P:1)
	at z2.a.g(P:11)
	at p3.a.b(P:1)
	at com.fankes.coloros.notify.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(P:24)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at H.afterHookedMethod(Unknown Source:104)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1262)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2776)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2768)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7128)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:103)
	at LSPHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1600(ActivityThread.java:314)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2176)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:269)
	at android.app.ActivityThread.main(ActivityThread.java:8301)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)

</code></pre></details>

**Comment by luckyzyx** [comment]
com.oplusos.systemui.statusbar.phone.OplusNotificationIconAreaController
-->
com.android.systemui.statusbar.phone.NotificationIconAreaController
updateIconsForLayout

**Comment by fankes** [comment]
前面那个方法是原生的，后面的是coloros自己实现的，之前的类不生效，不知道做了啥手脚，于是hook后面的，综上，没必要改

**Comment by fankes** [comment]
另外，这个是 bug，预计今晚修复完成

**Comment by luckyzyx** [comment]
抱歉，我应该找错类了，233，我这边有两个类
com.android.systemui.statusbar.phone.NotificationIconAreaController
com.oplusos.systemui.statusbar.policy.OplusNotificationIconAreaController
下面这个应该才是，哈哈

**Comment by fankes** [comment]
不是 `com.oplusos.systemui.statusbar.policy.OplusNotificationIconAreaController`
是 `com.oplusos.systemui.statusbar.phone.OplusNotificationIconAreaController` 吧

**Comment by fankes** [comment]
你把你的 SystemUI.apk 丢上来看看？

**Comment by luckyzyx** [comment]
[蓝奏云链接](https://luckyzyx.lanzouu.com/iXsOM02mcxuf)

**Comment by fankes** [comment]
> 我看了下旧版的是phone，我更新系统后搜到的确实是policy [蓝奏云链接](https://luckyzyx.lanzouu.com/iXsOM02mcxuf)

收到，等我看看

**Comment by luckyzyx** [comment]
> > 抱歉，我应该找错类了，233，我这边有两个类 com.android.systemui.statusbar.phone.NotificationIconAreaController com.oplusos.systemui.statusbar.policy.OplusNotificationIconAreaController 下面这个应该才是，哈哈
> 
> 你是对的，我已经收集了三个类名了，不是改类名就完事了，里面的内容也不一样，等我修吧

收到，晚安

**Comment by fankes** [comment]
> > > 抱歉，我应该找错类了，233，我这边有两个类 com.android.systemui.statusbar.phone.NotificationIconAreaController com.oplusos.systemui.statusbar.policy.OplusNotificationIconAreaController 下面这个应该才是，哈哈
> > 
> > 
> > 你是对的，我已经收集了三个类名了，不是改类名就完事了，里面的内容也不一样，等我修吧
> 
> 收到，晚安

啊这，晚安

**Comment by fankes** [comment]
新版本已发，问题已修复
