### ISSUE TITLE
[待解决] Android 13 适配问题

### ISSUE THREAD

**Issue by HapeLee** [fankes/ColorOSNotifyIcon#49]
**系统版本(必填)**

* V13 LE2120_11_F.03

**系统类型(请保留一个)**

* ColorOS

**Android 版本(必填)**

* Android 13

**模块版本(必填)**

* 1.85

**使用的 Xposed 框架名称与框架版本(必填)**

* LSPosed Zygisk 1.83(6597)

**同时使用的带有系统界面作用域的 Xposed 模块(选填)**

* 无

**问题的具体描述**

* 开启模块后，打开QQ音乐会导致系统界面崩溃

**提供模块问题 Log 或必要 Log**

<details><summary>展开查看</summary><pre><code>

----part 3 start----
[ 2022-08-23T00:44:33.973    10212: 19892: 19892 I/LSPosed-Bridge  ] [ColorOSNotify][E]--> [com.android.systemui] Try to hook class com.android.systemui.statusbar.notification.NotificationUtils[public static boolean com.android.systemui.statusbar.notification.NotificationUtils.isGrayscaleOplus(android.widget.ImageView,com.oplusos.util.OplusContrastColorUtil)] got an Exception [Default]
[ 2022-08-23T00:44:33.974    10212: 19892: 19892 E/LSPosed-Bridge  ] java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at a3.c$b$a.a(P:2)
	at a3.c$b$a.e(Unknown Source:5)
	at a3.c$b$a.b(Unknown Source:5)
	at m1.d.Q(P:13)
	at m1.d.B(Unknown Source:0)
	at m1.d$k.c(Unknown Source:26)
	at m1.d$k.a(Unknown Source:2)
	at z2.b$b$d.b(P:4)
	at r3.a$b$e.replaceHookedMethod(Unknown Source:14)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(Unknown Source:0)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.isGrayscaleOplus(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.updateIconColor(NotificationHeaderViewWrapper.java:260)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.resolveHeaderViews(NotificationHeaderViewWrapper.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.resolveHeaderViews(Unknown Source:8)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.<init>(NotificationHeaderViewWrapper.java:161)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationTemplateViewWrapper.<init>(NotificationTemplateViewWrapper.java:94)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationMediaTemplateViewWrapper.<init>(NotificationMediaTemplateViewWrapper.java:35)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationViewWrapper.wrap(NotificationViewWrapper.java:131)
	at com.android.systemui.statusbar.notification.row.NotificationContentView.setContractedChild(NotificationContentView.java:499)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.finishIfDone(NotificationContentInflater.java:641)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.access$1400(NotificationContentInflater.java:67)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater$5.onViewApplied(NotificationContentInflater.java:563)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5830)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5738)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
Caused by: java.lang.IllegalStateException: unable to getPixels(), pixel access is not supported on Config#HARDWARE bitmaps
	at android.graphics.Bitmap.checkHardware(Bitmap.java:425)
	at android.graphics.Bitmap.getPixels(Bitmap.java:1985)
	at com.android.internal.util.ImageUtils.isGrayscale(ImageUtils.java:96)
	at com.android.internal.util.ContrastColorUtil.isGrayscaleIcon(ContrastColorUtil.java:104)
	at com.android.internal.util.ContrastColorUtil.isGrayscaleIcon(ContrastColorUtil.java:129)
	... 39 more
[ 2022-08-23T00:44:33.980    10212: 19892: 19892 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at LSPHooker_.isGrayscaleOplus(Unknown Source:17)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.updateIconColor(NotificationHeaderViewWrapper.java:260)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.resolveHeaderViews(NotificationHeaderViewWrapper.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.resolveHeaderViews(Unknown Source:8)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.<init>(NotificationHeaderViewWrapper.java:161)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationTemplateViewWrapper.<init>(NotificationTemplateViewWrapper.java:94)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationMediaTemplateViewWrapper.<init>(NotificationMediaTemplateViewWrapper.java:35)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationViewWrapper.wrap(NotificationViewWrapper.java:131)
	at com.android.systemui.statusbar.notification.row.NotificationContentView.setContractedChild(NotificationContentView.java:499)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.finishIfDone(NotificationContentInflater.java:641)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.access$1400(NotificationContentInflater.java:67)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater$5.onViewApplied(NotificationContentInflater.java:563)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5830)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5738)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
[ 2022-08-23T00:44:34.415    10212: 21280: 21280 I/LSPosed-Bridge  ] Loading module com.fankes.coloros.notify from /data/app/~~oajdjDTo7-BYPOeRyziOLg==/com.fankes.coloros.notify-QeECcmLs6rBc_TIMrCWtLA==/base.apk
[ 2022-08-23T00:44:34.424    10212: 21280: 21280 I/LSPosed-Bridge  ]   Loading class com.fankes.coloros.notify.hook.HookEntry_YukiHookXposedInit
[ 2022-08-23T00:44:38.609    10212: 21280: 21280 I/LSPosed-Bridge  ] [ColorOSNotify][E]--> [com.android.systemui] Try to hook class com.android.systemui.statusbar.notification.NotificationUtils[public static boolean com.android.systemui.statusbar.notification.NotificationUtils.isGrayscaleOplus(android.widget.ImageView,com.oplusos.util.OplusContrastColorUtil)] got an Exception [Default]
[ 2022-08-23T00:44:38.610    10212: 21280: 21280 E/LSPosed-Bridge  ] java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at a3.c$b$a.a(P:2)
	at a3.c$b$a.e(Unknown Source:5)
	at a3.c$b$a.b(Unknown Source:5)
	at m1.d.Q(P:13)
	at m1.d.B(Unknown Source:0)
	at m1.d$k.c(Unknown Source:26)
	at m1.d$k.a(Unknown Source:2)
	at z2.b$b$d.b(P:4)
	at r3.a$b$e.replaceHookedMethod(Unknown Source:14)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(Unknown Source:0)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.isGrayscaleOplus(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.updateIconColor(NotificationHeaderViewWrapper.java:260)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.resolveHeaderViews(NotificationHeaderViewWrapper.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.resolveHeaderViews(Unknown Source:8)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.<init>(NotificationHeaderViewWrapper.java:161)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationTemplateViewWrapper.<init>(NotificationTemplateViewWrapper.java:94)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationMediaTemplateViewWrapper.<init>(NotificationMediaTemplateViewWrapper.java:35)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationViewWrapper.wrap(NotificationViewWrapper.java:131)
	at com.android.systemui.statusbar.notification.row.NotificationContentView.setContractedChild(NotificationContentView.java:499)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.finishIfDone(NotificationContentInflater.java:641)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.access$1400(NotificationContentInflater.java:67)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater$5.onViewApplied(NotificationContentInflater.java:563)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5830)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5738)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
Caused by: java.lang.IllegalStateException: unable to getPixels(), pixel access is not supported on Config#HARDWARE bitmaps
	at android.graphics.Bitmap.checkHardware(Bitmap.java:425)
	at android.graphics.Bitmap.getPixels(Bitmap.java:1985)
	at com.android.internal.util.ImageUtils.isGrayscale(ImageUtils.java:96)
	at com.android.internal.util.ContrastColorUtil.isGrayscaleIcon(ContrastColorUtil.java:104)
	at com.android.internal.util.ContrastColorUtil.isGrayscaleIcon(ContrastColorUtil.java:129)
	... 39 more
[ 2022-08-23T00:44:38.612    10212: 21280: 21280 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at LSPHooker_.isGrayscaleOplus(Unknown Source:17)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.updateIconColor(NotificationHeaderViewWrapper.java:260)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.resolveHeaderViews(NotificationHeaderViewWrapper.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.resolveHeaderViews(Unknown Source:8)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.<init>(NotificationHeaderViewWrapper.java:161)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationTemplateViewWrapper.<init>(NotificationTemplateViewWrapper.java:94)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationMediaTemplateViewWrapper.<init>(NotificationMediaTemplateViewWrapper.java:35)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationViewWrapper.wrap(NotificationViewWrapper.java:131)
	at com.android.systemui.statusbar.notification.row.NotificationContentView.setContractedChild(NotificationContentView.java:499)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.finishIfDone(NotificationContentInflater.java:641)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.access$1400(NotificationContentInflater.java:67)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater$5.onViewApplied(NotificationContentInflater.java:563)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5830)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5738)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
[ 2022-08-23T00:44:38.853    10212: 21614: 21614 I/LSPosed-Bridge  ] Loading module com.fankes.coloros.notify from /data/app/~~oajdjDTo7-BYPOeRyziOLg==/com.fankes.coloros.notify-QeECcmLs6rBc_TIMrCWtLA==/base.apk
[ 2022-08-23T00:44:38.860    10212: 21614: 21614 I/LSPosed-Bridge  ]   Loading class com.fankes.coloros.notify.hook.HookEntry_YukiHookXposedInit
[ 2022-08-23T00:44:42.826    10212: 21614: 21614 I/LSPosed-Bridge  ] [ColorOSNotify][E]--> [com.android.systemui] Try to hook class com.android.systemui.statusbar.notification.NotificationUtils[public static boolean com.android.systemui.statusbar.notification.NotificationUtils.isGrayscaleOplus(android.widget.ImageView,com.oplusos.util.OplusContrastColorUtil)] got an Exception [Default]
[ 2022-08-23T00:44:42.826    10212: 21614: 21614 E/LSPosed-Bridge  ] java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at a3.c$b$a.a(P:2)
	at a3.c$b$a.e(Unknown Source:5)
	at a3.c$b$a.b(Unknown Source:5)
	at m1.d.Q(P:13)
	at m1.d.B(Unknown Source:0)
	at m1.d$k.c(Unknown Source:26)
	at m1.d$k.a(Unknown Source:2)
	at z2.b$b$d.b(P:4)
	at r3.a$b$e.replaceHookedMethod(Unknown Source:14)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(Unknown Source:0)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:79)
	at LSPHooker_.isGrayscaleOplus(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.updateIconColor(NotificationHeaderViewWrapper.java:260)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.resolveHeaderViews(NotificationHeaderViewWrapper.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.resolveHeaderViews(Unknown Source:8)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.<init>(NotificationHeaderViewWrapper.java:161)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationTemplateViewWrapper.<init>(NotificationTemplateViewWrapper.java:94)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationMediaTemplateViewWrapper.<init>(NotificationMediaTemplateViewWrapper.java:35)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationViewWrapper.wrap(NotificationViewWrapper.java:131)
	at com.android.systemui.statusbar.notification.row.NotificationContentView.setContractedChild(NotificationContentView.java:499)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.finishIfDone(NotificationContentInflater.java:641)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.access$1400(NotificationContentInflater.java:67)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater$5.onViewApplied(NotificationContentInflater.java:563)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5830)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5738)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
Caused by: java.lang.IllegalStateException: unable to getPixels(), pixel access is not supported on Config#HARDWARE bitmaps
	at android.graphics.Bitmap.checkHardware(Bitmap.java:425)
	at android.graphics.Bitmap.getPixels(Bitmap.java:1985)
	at com.android.internal.util.ImageUtils.isGrayscale(ImageUtils.java:96)
	at com.android.internal.util.ContrastColorUtil.isGrayscaleIcon(ContrastColorUtil.java:104)
	at com.android.internal.util.ContrastColorUtil.isGrayscaleIcon(ContrastColorUtil.java:129)
	... 39 more
[ 2022-08-23T00:44:42.829    10212: 21614: 21614 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at LSPHooker_.isGrayscaleOplus(Unknown Source:17)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.updateIconColor(NotificationHeaderViewWrapper.java:260)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.resolveHeaderViews(NotificationHeaderViewWrapper.java:219)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:110)
	at LSPHooker_.resolveHeaderViews(Unknown Source:8)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationHeaderViewWrapper.<init>(NotificationHeaderViewWrapper.java:161)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationTemplateViewWrapper.<init>(NotificationTemplateViewWrapper.java:94)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationMediaTemplateViewWrapper.<init>(NotificationMediaTemplateViewWrapper.java:35)
	at com.android.systemui.statusbar.notification.row.wrapper.NotificationViewWrapper.wrap(NotificationViewWrapper.java:131)
	at com.android.systemui.statusbar.notification.row.NotificationContentView.setContractedChild(NotificationContentView.java:499)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.finishIfDone(NotificationContentInflater.java:641)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater.access$1400(NotificationContentInflater.java:67)
	at com.android.systemui.statusbar.notification.row.NotificationContentInflater$5.onViewApplied(NotificationContentInflater.java:563)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5830)
	at android.widget.RemoteViews$AsyncApplyTask.onPostExecute(RemoteViews.java:5738)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
[ 2022-08-23T00:44:43.079    10212: 21886: 21886 I/LSPosed-Bridge  ] Loading module com.fankes.coloros.notify from /data/app/~~oajdjDTo7-BYPOeRyziOLg==/com.fankes.coloros.notify-QeECcmLs6rBc_TIMrCWtLA==/base.apk
[ 2022-08-23T00:44:43.085    10212: 21886: 21886 I/LSPosed-Bridge  ]   Loading class com.fankes.coloros.notify.hook.HookEntry_YukiHookXposedInit

</code></pre></details>

系统界面:https://wwd.lanzouy.com/inwUg0a1xgvc
密码:6ct3

**Comment by fankes** [comment]
已在交流群说明过，这是安卓13已知问题请等待修复

**Comment by fankes** [comment]
新版本已适配。
