### ISSUE TITLE
ColorOS 14 点击右上角重启系统界面无效

### ISSUE THREAD

**Issue by ArielHeleneto** [fankes/ColorOSNotifyIcon#63]
### 模块版本

commit 41cf6a2

### 系统类型

ColorOS

### 系统版本

ColorOS 14.0 PHP110_14.0.0.83(CN01)

### Android 版本

14

### Xposed 框架名称与版本号

LSPosed 1.9.2(7038)

### 与系统界面(系统 UI)同作用域的 Xposed 模块

LuckyTool 1.1.4

### 详细描述问题发生的具体原因

在 LSPosed 1.9.2(7038) 中激活模块，并在 KernelSU 中提供 root 权限。打开模块并点击右上角按钮。

结果：系统界面重启，应用内提示“模块已激活，请重启系统...”

另外，点击导出调试日志无效。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

----part 2 start----
[ 2023-11-18T13:35:33.391    10189: 11563: 11563 I/LSPosed-Bridge  ] Loading legacy module com.luckyzyx.luckytool from /data/app/~~RWk_qR2Y0BPgS9G2n7wUDw==/com.luckyzyx.luckytool-Ezrfx-oGJPcgAtx35iiYZA==/base.apk
[ 2023-11-18T13:35:33.400    10189: 11563: 11563 I/LSPosed-Bridge  ]   Loading class com.luckyzyx.luckytool.hook.MainHook_YukiHookXposedInit
[ 2023-11-18T13:35:33.457    10189: 11563: 11563 I/LSPosed-Bridge  ] Loading legacy module com.fankes.coloros.notify from /data/app/~~Jhemb6bjYPa_dQXic7bLyQ==/com.fankes.coloros.notify-dV1DV9BchlESH3tlAWGV-Q==/base.apk
[ 2023-11-18T13:35:33.466    10189: 11563: 11563 I/LSPosed-Bridge  ]   Loading class com.fankes.coloros.notify.hook.HookEntry_YukiHookXposedInit
[ 2023-11-18T13:35:33.725    10189: 11563: 11563 I/LSPosed-Bridge  ] [E] An exception occurred in the Hooking Process of YukiHookAPI
[ 2023-11-18T13:35:33.725    10189: 11563: 11563 E/LSPosed-Bridge  ] java.lang.IllegalStateException: VariousClass match failed of those ["com.oplusos.systemui.statusbar.policy.SystemPromptController","com.coloros.systemui.statusbar.policy.ColorSystemPromptController"]
	at b3.d.a(P:55)
	at r3.a.a(P:56)
	at r3.a$a.c(P:1)
	at r1.d.D0(P:9)
	at r1.d.x(P:7)
	at q3.a.w(P:8)
	at u3.b.t(P:142)
	at q1.a$a.a(P:84)
	at q1.a$a.o(P:3)
	at b4.a.m(P:137)
	at c4.a.d(P:9)
	at q1.b.c(P:167)
	at q1.b.d(P:17)
	at q1.b.a(P:13)
	at com.fankes.coloros.notify.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(P:3)
	at zPwwSebULNp.j.hQNLk.mg.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at zPwwSebULNp.j.hQNLk.mg.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at zPwwSebULNp.j.hQNLk.mg.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:281)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1168)
	at android.app.LoadedApk.getResources(LoadedApk.java:1420)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3400)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3392)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7428)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8819)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

</code></pre></details>

### 确认一下你提交的信息

- [X] 我确保上述信息准确无误

**Comment by fankes** [comment]
14 没有适配，且我没有对应的系统和设备，所以大概等我有空了更新 14 再修复
